spring:
  profiles:
    active: dev

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

logging.level:
  org.hibernate.SQL: debug
---
spring:
  profiles: local


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000

property:
  video:
    url: /Users/joohyuk/Movies/
    uploadFolder: upload_video/

---
spring:
  profiles: dev

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true
        default_batch_fetch_size: 1000

  datasource:
    url: jdbc:mysql://localhost:3306/video_service?serverTimezone=UTC&characterEncoding=UTF-8
    username: connectuser
    password: connect123!@#

property:
  video:
    url: /Users/joohyuk/Movies/
    uploadFolder: upload_video/

---
spring:
  profiles: test

property:
  video:
    url: /Users/joohyuk/Movies/
    uploadFolder: upload_video/
