
spring:
  profiles:
    active: local

  thymeleaf:
    cache: false

  devtools:
    remote:
      restart:
        enabled: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
property:
  video:
    url: /Users/joohyuk/Movies/
    uploadFolder: upload_video/

logging.level:
  org.hibernate.SQL: debug
---
spring:
  profiles: test